version: 2

# dry:
#   restore_shards_cache: &restore_shards_cache
#     keys:
#       - shards-cache-v1-{{ .Branch }}-{{ checksum "shard.lock" }}
#       - shards-cache-v1-{{ .Branch }}
#       - shards-cache-v1

#   save_shards_cache: &save_shards_cache
#     key: shards-cache-v1-{{ .Branch }}-{{ checksum "shard.lock" }}
#     paths:
#       - ./shards-cache

jobs:
  test:
    docker:
      - image: crystallang/crystal:latest
        # environment:
        #   SHARDS_CACHE_PATH: ./shards-cache
    steps:
      - run: crystal --version

      - checkout

      # - restore_cache: *restore_shards_cache
      - run: shards
      # - save_cache: *save_shards_cache

      - run: crystal spec

workflows:
  version: 2
  ci:
    jobs:
      - test
